In [19]:
import pandas as pd

In [20]:
# importing blinkit csv file

df = pd.read_csv("blinkit_grocery_sales.csv")

df.head(10)

,Item Fat Content,Item Identifier,Item Type,Outlet Establishment Year,Outlet Identifier,Outlet Location Type,Outlet Size,Outlet Type,Item Visibility,Item Weight,Sales,Rating
0,Regular,FDX32,Fruits and Vegetables,2012,OUT049,Tier 1,Medium,Supermarket Type1,0.100014,15.10,145.4786,5.0
1,Low Fat,NCB42,Health and Hygiene,2022,OUT018,Tier 3,Medium,Supermarket Type2,0.008596,11.80,115.3492,5.0
2,Regular,FDR28,Frozen Foods,2016,OUT046,Tier 1,Small,Supermarket Type1,0.025896,13.85,165.0210,5.0
3,Regular,FDL50,Canned,2014,OUT013,Tier 3,High,Supermarket Type1,0.042278,12.15,126.5046,5.0
4,Low Fat,DRI25,Soft Drinks,2015,OUT045,Tier 2,Small,Supermarket Type1,0.033970,19.60,55.1614,5.0
5,low fat,FDS52,Frozen Foods,2020,OUT017,Tier 2,Small,Supermarket Type1,0.005505,8.89,102.4016,5.0
6,Low Fat,NCU05,Health and Hygiene,2011,OUT010,Tier 3,Small,Grocery Store,0.098312,11.80,81.4618,5.0
7,Low Fat,NCD30,Household,2015,OUT045,Tier 2,Small,Supermarket Type1,0.026904,19.70,96.0726,5.0
8,Low Fat,FDW20,Fruits and Vegetables,2014,OUT013,Tier 3,High,Supermarket Type1,0.024129,20.75,124.1730,5.0
9,Low Fat,FDX25,Canned,2018,OUT027,Tier 3,Medium,Supermarket Type3,0.101562,NaN,181.9292,5.0

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8523 entries, 0 to 8522
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Item Fat Content           8523 non-null   str
 1   Item Identifier            8523 non-null   str
 2   Item Type                  8523 non-null   str
 3   Outlet Establishment Year  8523 non-null   int64
 4   Outlet Identifier          8523 non-null   str
 5   Outlet Location Type       8523 non-null   str
 6   Outlet Size                8523 non-null   str
 7   Outlet Type                8523 non-null   str
 8   Item Visibility            8523 non-null   float64
 9   Item Weight                7060 non-null   float64
 10  Sales                      8523 non-null   float64
 11  Rating                     8523 non-null   float64
dtypes: float64(4), int64(1), str(7)
memory usage: 799.2 KB

In [4]:
df.describe(include= 'all')

,Item Fat Content,Item Identifier,Item Type,Outlet Establishment Year,Outlet Identifier,Outlet Location Type,Outlet Size,Outlet Type,Item Visibility,Item Weight,Sales,Rating
count,8523,8523,8523,8523.000000,8523,8523,8523,8523,8523.000000,7060.000000,8523.000000,8523.000000
unique,5,1559,16,NaN,10,3,3,4,NaN,NaN,NaN,NaN
top,Low Fat,FDW13,Fruits and Vegetables,NaN,OUT027,Tier 3,Medium,Supermarket Type1,NaN,NaN,NaN,NaN
freq,5089,10,1232,NaN,935,3350,3631,5577,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,2016.450546,NaN,NaN,NaN,NaN,0.066132,12.857645,140.992783,3.965857
std,NaN,NaN,NaN,3.189396,NaN,NaN,NaN,NaN,0.051598,4.643456,62.275067,0.605651
min,NaN,NaN,NaN,2011.000000,NaN,NaN,NaN,NaN,0.000000,4.555000,31.290000,1.000000
25%,NaN,NaN,NaN,2014.000000,NaN,NaN,NaN,NaN,0.026989,8.773750,93.826500,4.000000
50%,NaN,NaN,NaN,2016.000000,NaN,NaN,NaN,NaN,0.053931,12.600000,143.012800,4.000000
75%,NaN,NaN,NaN,2018.000000,NaN,NaN,NaN,NaN,0.094585,16.850000,185.643700,4.200000
max,NaN,NaN,NaN,2022.000000,NaN,NaN,NaN,NaN,0.328391,21.350000,266.888400,5.000000

In [5]:
# Display current column names
df.columns

Index(['Item Fat Content', 'Item Identifier', 'Item Type',
       'Outlet Establishment Year', 'Outlet Identifier',
       'Outlet Location Type', 'Outlet Size', 'Outlet Type', 'Item Visibility',
       'Item Weight', 'Sales', 'Rating'],
      dtype='str')

In [27]:
# Convert column names to snake_case
df.columns = (
    df.columns.str.strip()
    .str.lower()
    .str.replace(' ', '_')
    )

df.columns

Index(['item_fat_content', 'item_identifier', 'item_type',
       'outlet_establishment_year', 'outlet_identifier',
       'outlet_location_type', 'outlet_size', 'outlet_type', 'item_visibility',
       'item_weight', 'sales', 'rating', 'sales_category'],
      dtype='str')

In [7]:
# checking null values

df.isnull().sum()

item_fat_content                0
item_identifier                 0
item_type                       0
outlet_establishment_year       0
outlet_identifier               0
outlet_location_type            0
outlet_size                     0
outlet_type                     0
item_visibility                 0
item_weight                  1463
sales                           0
rating                          0
dtype: int64

# The 'item_weight' column contained missing values that could impact downstream analysis. Since product weight is a fixed attribute for each product, missing values were first imputed using the average weight of the corresponding 'item_identifier'. Any remaining missing values were then filled using the median weight of the respective 'item_type' to maintain realistic product characteristics while minimizing bias.

In [28]:
df['item_weight'] = df.groupby('item_identifier')['item_weight'].transform(
    lambda x: x.fillna(x.mean())
)

df.isnull().sum()

item_fat_content             0
item_identifier              0
item_type                    0
outlet_establishment_year    0
outlet_identifier            0
outlet_location_type         0
outlet_size                  0
outlet_type                  0
item_visibility              0
item_weight                  4
sales                        0
rating                       0
sales_category               0
dtype: int64

In [29]:
# remaining null value in 'item_weight' is filled by the median weight of corresponding 'item_type'

df['item_weight'] = df.groupby('item_type')['item_weight'].transform(
    lambda x: x.fillna(x.median())
)

df['item_weight'].isnull().sum()

np.int64(0)

In [30]:
df.head(10)

,item_fat_content,item_identifier,item_type,outlet_establishment_year,outlet_identifier,outlet_location_type,outlet_size,outlet_type,item_visibility,item_weight,sales,rating,sales_category
0,Regular,FDX32,Fruits and Vegetables,2012,OUT049,Tier 1,Medium,Supermarket Type1,0.100014,15.10,145.4786,5.0,Medium
1,Low Fat,NCB42,Health and Hygiene,2022,OUT018,Tier 3,Medium,Supermarket Type2,0.008596,11.80,115.3492,5.0,Medium
2,Regular,FDR28,Frozen Foods,2016,OUT046,Tier 1,Small,Supermarket Type1,0.025896,13.85,165.0210,5.0,Medium
3,Regular,FDL50,Canned,2014,OUT013,Tier 3,High,Supermarket Type1,0.042278,12.15,126.5046,5.0,Medium
4,Low Fat,DRI25,Soft Drinks,2015,OUT045,Tier 2,Small,Supermarket Type1,0.033970,19.60,55.1614,5.0,Low
5,low fat,FDS52,Frozen Foods,2020,OUT017,Tier 2,Small,Supermarket Type1,0.005505,8.89,102.4016,5.0,Low
6,Low Fat,NCU05,Health and Hygiene,2011,OUT010,Tier 3,Small,Grocery Store,0.098312,11.80,81.4618,5.0,Low
7,Low Fat,NCD30,Household,2015,OUT045,Tier 2,Small,Supermarket Type1,0.026904,19.70,96.0726,5.0,Low
8,Low Fat,FDW20,Fruits and Vegetables,2014,OUT013,Tier 3,High,Supermarket Type1,0.024129,20.75,124.1730,5.0,Medium
9,Low Fat,FDX25,Canned,2018,OUT027,Tier 3,Medium,Supermarket Type3,0.101562,16.70,181.9292,5.0,High

# checking unique values in 'item_fat_content' columns to identify inconsistent name conventions and spelling variations.

In [31]:
df["item_fat_content"].unique()

<StringArray>
['Regular', 'Low Fat', 'low fat', 'LF', 'reg']
Length: 5, dtype: str

# replacing different name of the same category

In [32]:
df["item_fat_content"] = df["item_fat_content"].replace({
    "LF":"Low Fat",
    "low fat":"Low Fat",
    "reg":"Regular"
    })

# checking again

print(df["item_fat_content"].unique())

<StringArray>
['Regular', 'Low Fat']
Length: 2, dtype: str

# investigating products with zero visibility values.

In [33]:
df[df["item_visibility"] == 0][["item_identifier", "item_type", "sales", "item_visibility"]].head()

    item_identifier              item_type     sales  item_visibility
20            FDZ07  Fruits and Vegetables   60.2194              0.0
59            FDC44  Fruits and Vegetables  111.9518              0.0
79            FDV26                  Dairy  194.2794              0.0
98            NCK29     Health and Hygiene  123.4730              0.0
113           FDE41           Frozen Foods   83.7566              0.0

# products with zero visibility were found to have recorded sales,
# suggesting that zero values likely represent missing or incorectly recorded data. 
# these values were replaced with median visibility of products within the same item category

In [34]:
df["item_visibility"] = df.groupby("item_type")["item_visibility"].transform(
    lambda x:x.replace(0,x[x > 0].median())
)

# creating sales category based on sales distribution for easier segementation and dashboard filtering

In [42]:
df["sales_category"] = pd.qcut(df["sales"],q=3, labels=["Low", "Medium", "High"])

# checking

df.head()

,item_fat_content,item_identifier,item_type,outlet_establishment_year,outlet_identifier,outlet_location_type,outlet_size,outlet_type,item_visibility,item_weight,sales,rating,sales_category
0,Regular,FDX32,Fruits and Vegetables,2012,OUT049,Tier 1,Medium,Supermarket Type1,0.100014,15.10,145.4786,5.0,Medium
1,Low Fat,NCB42,Health and Hygiene,2022,OUT018,Tier 3,Medium,Supermarket Type2,0.008596,11.80,115.3492,5.0,Medium
2,Regular,FDR28,Frozen Foods,2016,OUT046,Tier 1,Small,Supermarket Type1,0.025896,13.85,165.0210,5.0,Medium
3,Regular,FDL50,Canned,2014,OUT013,Tier 3,High,Supermarket Type1,0.042278,12.15,126.5046,5.0,Medium
4,Low Fat,DRI25,Soft Drinks,2015,OUT045,Tier 2,Small,Supermarket Type1,0.033970,19.60,55.1614,5.0,Low

# creating outlet_age to analyze whether older outlets perform differently from newer outlets.

In [44]:
current_year = 2026

df["outlet_age"] = current_year - df["outlet_establishment_year"]

#checking

df.head()

,item_fat_content,item_identifier,item_type,outlet_establishment_year,outlet_identifier,outlet_location_type,outlet_size,outlet_type,item_visibility,item_weight,sales,rating,sales_category,outlet_age
0,Regular,FDX32,Fruits and Vegetables,2012,OUT049,Tier 1,Medium,Supermarket Type1,0.100014,15.10,145.4786,5.0,Medium,14
1,Low Fat,NCB42,Health and Hygiene,2022,OUT018,Tier 3,Medium,Supermarket Type2,0.008596,11.80,115.3492,5.0,Medium,4
2,Regular,FDR28,Frozen Foods,2016,OUT046,Tier 1,Small,Supermarket Type1,0.025896,13.85,165.0210,5.0,Medium,10
3,Regular,FDL50,Canned,2014,OUT013,Tier 3,High,Supermarket Type1,0.042278,12.15,126.5046,5.0,Medium,12
4,Low Fat,DRI25,Soft Drinks,2015,OUT045,Tier 2,Small,Supermarket Type1,0.033970,19.60,55.1614,5.0,Low,11

# final validation check

In [45]:
df.isnull().sum()

item_fat_content             0
item_identifier              0
item_type                    0
outlet_establishment_year    0
outlet_identifier            0
outlet_location_type         0
outlet_size                  0
outlet_type                  0
item_visibility              0
item_weight                  0
sales                        0
rating                       0
sales_category               0
outlet_age                   0
dtype: int64

In [46]:
df.shape

(8523, 14)

In [47]:
df.dtypes

item_fat_content                  str
item_identifier                   str
item_type                         str
outlet_establishment_year       int64
outlet_identifier                 str
outlet_location_type              str
outlet_size                       str
outlet_type                       str
item_visibility               float64
item_weight                   float64
sales                         float64
rating                        float64
sales_category               category
outlet_age                      int64
dtype: object

In [50]:
df.describe()

,outlet_establishment_year,item_visibility,item_weight,sales,rating,outlet_age
count,8523.000000,8523.000000,8523.000000,8523.000000,8523.000000,8523.000000
mean,2016.450546,0.069673,12.875361,140.992783,3.965857,9.549454
std,3.189396,0.048855,4.645031,62.275067,0.605651,3.189396
min,2011.000000,0.003575,4.555000,31.290000,1.000000,4.000000
25%,2014.000000,0.033085,8.785000,93.826500,4.000000,8.000000
50%,2016.000000,0.058034,12.650000,143.012800,4.000000,10.000000
75%,2018.000000,0.094585,16.850000,185.643700,4.200000,12.000000
max,2022.000000,0.328391,21.350000,266.888400,5.000000,15.000000

In [51]:
df.head(10)

,item_fat_content,item_identifier,item_type,outlet_establishment_year,outlet_identifier,outlet_location_type,outlet_size,outlet_type,item_visibility,item_weight,sales,rating,sales_category,outlet_age
0,Regular,FDX32,Fruits and Vegetables,2012,OUT049,Tier 1,Medium,Supermarket Type1,0.100014,15.10,145.4786,5.0,Medium,14
1,Low Fat,NCB42,Health and Hygiene,2022,OUT018,Tier 3,Medium,Supermarket Type2,0.008596,11.80,115.3492,5.0,Medium,4
2,Regular,FDR28,Frozen Foods,2016,OUT046,Tier 1,Small,Supermarket Type1,0.025896,13.85,165.0210,5.0,Medium,10
3,Regular,FDL50,Canned,2014,OUT013,Tier 3,High,Supermarket Type1,0.042278,12.15,126.5046,5.0,Medium,12
4,Low Fat,DRI25,Soft Drinks,2015,OUT045,Tier 2,Small,Supermarket Type1,0.033970,19.60,55.1614,5.0,Low,11
5,Low Fat,FDS52,Frozen Foods,2020,OUT017,Tier 2,Small,Supermarket Type1,0.005505,8.89,102.4016,5.0,Low,6
6,Low Fat,NCU05,Health and Hygiene,2011,OUT010,Tier 3,Small,Grocery Store,0.098312,11.80,81.4618,5.0,Low,15
7,Low Fat,NCD30,Household,2015,OUT045,Tier 2,Small,Supermarket Type1,0.026904,19.70,96.0726,5.0,Low,11
8,Low Fat,FDW20,Fruits and Vegetables,2014,OUT013,Tier 3,High,Supermarket Type1,0.024129,20.75,124.1730,5.0,Medium,12
9,Low Fat,FDX25,Canned,2018,OUT027,Tier 3,Medium,Supermarket Type3,0.101562,16.70,181.9292,5.0,High,8

In [52]:
pip install sqlalchemy psycopg2-binary

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: sqlalchemy in C:\Users\xsidd\AppData\Roaming\Python\Python314\site-packages (2.0.50)
Requirement already satisfied: psycopg2-binary in C:\Users\xsidd\AppData\Roaming\Python\Python314\site-packages (2.9.12)
Requirement already satisfied: greenlet>=1 in C:\Users\xsidd\AppData\Roaming\Python\Python314\site-packages (from sqlalchemy) (3.5.1)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\xsidd\AppData\Roaming\Python\Python314\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [54]:
# connecting python to postgresql 

from sqlalchemy import create_engine

engine = create_engine(
    "postgresql+psycopg2://postgres:xsiddsql@localhost:5432/blinkit_project"
)

In [56]:
# sending dataframe to postgre sql
df.to_sql(
    name="blinkit_sales",
    con=engine,
    if_exists="replace",
    index=False
)

523